stages:
    - build

#before_script:
#    - cd ios    

variables:
#    LC_ALL: "en_US.UTF-8"
#    LANG: "en_US.UTF-8"
#    GIT_STRATEGY: clone

build:
    stage: build
    script:
        - pwd
#        - ls
        - cd ios            
        - ls
        - pwd
#        - bundle install
#        - BUNDLE_GEMFILE="/ios/Gemfile" ./bundle install
#    - bundle exec fastlane medicoconsultorbuild
#  artifacts:
#    paths:
#    - ./*.ipa

